DROP VIEW GR3_V_ASIGNATURAS_SIMPLE;
DROP VIEW GR3_V_PROF_SIMPLE;
DROP VIEW GR3_V_PROFESORES_ASG;
DROP VIEW GR3_V_PROF_EXCLUSIVO;

DROP TABLE GR3_PROF_EXCLUSIVO;
DROP TABLE GR3_ASIGNATURA_PROFESOR;
DROP TABLE GR3_PROF_SIMPLE;
DROP TABLE GR3_ASIGNATURA;
DROP TABLE GR3_PROFESOR;

DROP FUNCTION TRFN_GR3_ASIGNAR_CANTIDAD;
DROP FUNCTION TRFN_GR3_ACTUALIZAR_VISTA_V_PROF_EXCLUSIVO;
DROP FUNCTION TRFN_GR3_ACTUALIZAR_VISTA_V_PROF_SIMPLE;
DROP FUNCTION TRFN_GR3_ACTUALIZAR_ASIGNATURA;